### ISSUE TITLE
(feature request) Allow spdx file to be set as input.

### ISSUE THREAD

**Issue by soimsoim** [aboutcode-org/scancode-workbench#425]
### Description
* This tool is a great tool to see the results of license analysis.
* How about reading spdx files as well as scancode analysis results?

**Comment by mjherzog** [comment]
I am not sure that this makes sense because:
- The ScanCode Workbench is closely tied to the ScanCode Toolkit data model which is very different from the SPDX data model.
- A Scan file from ScanCode represents data actually found in a Codebase - this is often not the case for SPDX data.
It might be better to propose an SPDX File file-viewer/workbench as an SPDX enhancement.

**Comment by soimsoim** [comment]
The reason I asked for this feature is that this tool is so good that I wanted to see the output of other source code analysis tools through this tool.
Since most other source code analysis tools can print the results in SPDX format, I thought I could utilize this tool if this tool could read SPDX format as input.

However, depending on your comments, it may be appropriate to suggest the SPDX enhancement part on the SPDX tool side.

Thank you for your kind reply.
