### ISSUE TITLE
ChartSummaryView shows wrong summary for directory that is a substring of another

### ISSUE THREAD

**Issue by kkoehne** [aboutcode-org/scancode-workbench#457]
The Charts Overview page seems to sometimes show additional content from another directory that is similarly named. I could reproduce this e.g. for two different directories 'A', 'AA'.

### Description
I have a directory tree with two subdirectories, one named 'A' and another one named 'AA'
* I select 'A' in the directory tree, and select 'Chart Summary View' in the 'View menu'
* I select 'License Expressions' as a filter 
* It shows me also licenses that are actually in the 'AA' directory. Also clicking on any of the findings shows me no files.

### System configuration
* Windows 10
* ScanCode workbench version 3.1.1
* ScanCode version 3.1.1

**Comment by kkoehne** [comment]
![Workbench-issue-457](https://user-images.githubusercontent.com/1202002/88391552-b2775e80-cdba-11ea-816e-93368ba7ddae.PNG)

**Comment by kkoehne** [comment]
Minimal .json file to reproduce (packaged as a .zip, so I could actually upload it):

[workbench-issue-457.zip](https://github.com/nexB/scancode-workbench/files/4971926/workbench-issue-457.zip)

**Comment by pombredanne** [comment]
@kkoehne Thank you ++ for this report!

**Comment by steven-esser** [comment]
@kkoehne Thanks

**Comment by OmkarPh** [comment]
This issue has been fixed in the latest versions
You can try out here https://github.com/nexB/scancode-workbench/releases/latest

![image](https://github.com/nexB/scancode-workbench/assets/48476025/c734d0db-4d1f-4402-8081-61c1708c146a)
![image](https://github.com/nexB/scancode-workbench/assets/48476025/94662f9f-76b9-4590-9686-4c1624423e1b)
![image](https://github.com/nexB/scancode-workbench/assets/48476025/4ec15b37-af4f-4347-b1f5-4149f9bc6965)
